version: '3.8'

services:
  db:
    image: postgres:16-alpine 
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    ports:
      - "5433:5432" 
    expose:
      - "5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
   
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} 
    ports:
      - "8080:80"
    expose:
      - "8080"
    depends_on:
      - db
  
volumes:
  pgdata: 